-- RAW TABLE
CREATE TABLE HR_Employee_Attrition_Raw (
       Age INT,
       Attrition VARCHAR(10),
       BusinessTravel VARCHAR(50),
       DailyRate INT,
       Department VARCHAR(50),
       DistanceFromHome INT,
       Education INT,
       EducationField VARCHAR(50),
       EmployeeCount INT,
       EmployeeNumber INT,
       EnvironmentSatisfaction INT,
       Gender VARCHAR(20),
       HourlyRate INT,
       JobInvolvement INT,
       JobLevel INT,
       JobRole VARCHAR(50),
       JobSatisfaction INT,
       MaritalStatus VARCHAR(20),
       MonthlyIncome INT,
       MonthlyRate INT,
       NumCompaniesWorked INT,
       Over18 CHAR(1),
       OverTime VARCHAR(10),
       PercentSalaryHike INT,
       PerformanceRating INT,
       RelationshipSatisfaction INT,
       StandardHours INT,
       StockOptionLevel INT,
       TotalWorkingYears INT,
       TrainingTimesLastYear INT,
       WorkLifeBalance INT,
       YearsAtCompany INT,
       YearsInCurrentRole INT,
       YearsSinceLastPromotion INT,
       YearsWithCurrManager INT
);